// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/anneau/go-template/api/controller"
	"github.com/anneau/go-template/api/router"
)

// Injectors from wire.go:

func InitializeRouter() (*router.Router, error) {
	healthController, err := InitializeHealthController()
	if err != nil {
		return nil, err
	}
	routerRouter := &router.Router{
		HealthController: healthController,
	}
	return routerRouter, nil
}

func InitializeHealthController() (*controller.HealthController, error) {
	healthController := controller.NewHealthController()
	return healthController, nil
}
